-- // create_table_transaction
-- Migration SQL that makes the change goes here.
CREATE TABLE TRANSACTION (
	TRA_ID SERIAL,
	TRA_ACH_ID INTEGER REFERENCES ACHETEUR(ACH_ID) NOT NULL,
	TRA_OFF_ID INTEGER REFERENCES OFFRE(OFF_ID) NOT NULL,
	TRA_DATE TIMESTAMP NOT NULL,
	PRIMARY KEY (TRA_ID, TRA_ACH_ID, TRA_OFF_ID)
);


-- //@UNDO
-- SQL to undo the change goes here.
DROP TABLE TRANSACTION;
DROP SEQUENCE TRANSACTION_TRA_ID_SEQ;
