-- // insert_data
-- Migration SQL that makes the change goes here.
INSERT INTO UTILISATEUR (USR_LOGIN, USR_PASSWORD) VALUES ('user1', 'pass');
INSERT INTO UTILISATEUR (USR_LOGIN, USR_PASSWORD) VALUES ('userVendeur', 'pass');
INSERT INTO UTILISATEUR (USR_LOGIN, USR_PASSWORD) VALUES ('userVendeur2', 'pass');
INSERT INTO ACHETEUR (ACH_USR_ID, ACH_prenom, ACH_NOM, ACH_DATE_NAISSANCE) values (1, 'toto', 'totoName', '1962-06-16');
INSERT INTO VENDEUR (VEN_USR_ID, VEN_NOM_ENTREPRISE) VALUES (2, 'Best Entreprise');
INSERT INTO VENDEUR (VEN_USR_ID, VEN_NOM_ENTREPRISE) VALUES (3, 'MyEnterprise');
INSERT INTO PRODUIT (PRT_NOM) VALUES ('truc');
INSERT INTO PRODUIT (PRT_NOM) VALUES ('truc cool');
INSERT INTO OFFRE (OFF_PRT_ID, OFF_VEN_ID, OFF_QUANTITE, OFF_UNITE, OFF_PRIX_UNITE, OFF_DATE_CREATION) VALUES (1, 1, 5, 'KG', 10, '16-05-2011 15:36:38');
INSERT INTO OFFRE (OFF_PRT_ID, OFF_VEN_ID, OFF_QUANTITE, OFF_UNITE, OFF_PRIX_UNITE, OFF_DATE_CREATION) VALUES (2, 1, 6, 'L', 15, '17-05-2011 15:36:38');
INSERT INTO OFFRE (OFF_PRT_ID, OFF_VEN_ID, OFF_QUANTITE, OFF_UNITE, OFF_PRIX_UNITE, OFF_DATE_CREATION) VALUES (1, 1, 15, 'KG', 8, '18-05-2011 15:36:38');
INSERT INTO OFFRE (OFF_PRT_ID, OFF_VEN_ID, OFF_QUANTITE, OFF_UNITE, OFF_PRIX_UNITE, OFF_DATE_CREATION) VALUES (1, 1, 7, 'KG', 10, '19-05-2011 15:36:38');
INSERT INTO OFFRE (OFF_PRT_ID, OFF_VEN_ID, OFF_QUANTITE, OFF_UNITE, OFF_PRIX_UNITE, OFF_DATE_CREATION) VALUES (2, 1, 30, 'L', 15, '20-05-2011 15:36:38');
INSERT INTO OFFRE (OFF_PRT_ID, OFF_VEN_ID, OFF_QUANTITE, OFF_UNITE, OFF_PRIX_UNITE, OFF_DATE_CREATION) VALUES (1, 1, 67, 'KG', 8, '20-05-2011 15:36:38');
INSERT INTO TRANSACTION (TRA_ACH_ID, TRA_OFF_ID, TRA_DATE) VALUES (1, 1, '1962-08-16');
INSERT INTO TRANSACTION (TRA_ACH_ID, TRA_OFF_ID, TRA_DATE) VALUES (1, 2, '1962-08-17');
INSERT INTO TRANSACTION (TRA_ACH_ID, TRA_OFF_ID, TRA_DATE) VALUES (1, 3, '1962-08-18');


-- //@UNDO
-- SQL to undo the change goes here.


