spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/trainingBdd
    username: postgres
    password: postgres
    
---
  
spring:
  profiles: test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/trainingTestBdd
    username: postgres
    password: postgres
    